spring.application.name=portal
# ===== Database =====
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/lostfound_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:babita425}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===== JPA / Hibernate =====
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ===== Server =====
server.port=${PORT:8080}

# ===== JWT =====
jwt.secret=${JWT_SECRET:mWsDxa5jK5B8HoPKZ4g4iTjQ8wp2uXDI5IMYKq3/Dd64sQGiVCwjhZGhP++yzqksNA8xkWStWPTg2oZly2NEtA==    }
jwt.expiration=${JWT_EXPIRATION:86400000}

# ===== CORS =====
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

# ===== Cloudinary =====
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:drluzf4uo}
cloudinary.api-key=${CLOUDINARY_API_KEY:733222526261891}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:FiEYtqGeg42XZhTLgHg51zHXcRI}